FROM postgres:16.3

RUN apt-get update && apt-get  install -y postgresql-16-postgis-3  

COPY db_init.sql /docker-entrypoint-initdb.d/
RUN chmod a+r /docker-entrypoint-initdb.d/db_init.sql

CMD ["/usr/local/bin/docker-entrypoint.sh","postgres"]