version: '3'

services:
  debug:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - "sh"
      - "-c"
      - |
        pip install debugpy \
        && python3 -m debugpy --wait-for-client --listen 0.0.0.0:12345 -m uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - 8001:8001
      - 12345:12345
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - SKIP_MIGRATIONS=true
    networks:
      - backend-network

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network
    volumes:
      - ./app:/app
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile-db
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - db-volume:/db
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend-network:
    driver: bridge

volumes:
  db-volume:
