"""init

Revision ID: 465f2fbf30ea
Revises: 
Create Date: 2025-09-09 02:49:50.682429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '465f2fbf30ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caracteristicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caracteristicas_id'), 'caracteristicas', ['id'], unique=False)
    op.create_table('choferes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('borrado', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_index(op.f('ix_choferes_id'), 'choferes', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_documento'), 'clientes', ['documento'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('invitaciones_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_link', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitaciones_usuarios_email'), 'invitaciones_usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_invitaciones_usuarios_hash_link'), 'invitaciones_usuarios', ['hash_link'], unique=True)
    op.create_index(op.f('ix_invitaciones_usuarios_id'), 'invitaciones_usuarios', ['id'], unique=False)
    op.create_table('lugares_comunes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('borrado', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lugares_comunes_id'), 'lugares_comunes', ['id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_email'), 'password_reset_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('tipo_parada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_parada_id'), 'tipo_parada', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('capacidad_convencional', sa.Integer(), nullable=False),
    sa.Column('capacidad_silla_de_ruedas', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('borrado', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.CheckConstraint('capacidad_convencional > 0', name='capacidad_convencional_check'),
    sa.CheckConstraint('capacidad_silla_de_ruedas >= 0', name='capacidad_silla_de_ruedas_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_vehiculos_id'), 'vehiculos', ['id'], unique=False)
    op.create_table('clientes_caracteristicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_caracteristica', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_caracteristica'], ['caracteristicas.id'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_caracteristicas_id'), 'clientes_caracteristicas', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_documento', sa.Integer(), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('acompañante', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.Enum('solo_ida', 'solo_vuelta', 'ida_y_vuelta', name='tipopedido'), nullable=False),
    sa.Column('fecha_ingresado', sa.DateTime(), nullable=True),
    sa.Column('fecha_programado', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'asignado', 'rechazado', name='estadopedido'), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_documento'], ['clientes.documento'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('planificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('definitiva', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planificaciones_id'), 'planificaciones', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('vehiculos_caracteristicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=True),
    sa.Column('id_caracteristica', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_caracteristica'], ['caracteristicas.id'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_caracteristicas_id'), 'vehiculos_caracteristicas', ['id'], unique=False)
    op.create_table('paradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('posicion_en_pedido', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('ventana_horaria_inicio', sa.Time(), nullable=True),
    sa.Column('ventana_horaria_fin', sa.Time(), nullable=True),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['tipo'], ['tipo_parada.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paradas_id'), 'paradas', ['id'], unique=False)
    op.create_table('pedidos_no_atendidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_planificacion', sa.Integer(), nullable=True),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('no_enviado_al_optimizador', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['id_planificacion'], ['planificaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_no_atendidos_id'), 'pedidos_no_atendidos', ['id'], unique=False)
    op.create_table('rutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_planificacion', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_chofer', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('descanso_inicio', sa.Time(), nullable=True),
    sa.Column('descanso_fin', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id'], ),
    sa.ForeignKeyConstraint(['id_planificacion'], ['planificaciones.id'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutas_id'), 'rutas', ['id'], unique=False)
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_planificacion', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_planificacion'], ['planificaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnos_id'), 'turnos', ['id'], unique=False)
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=True),
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.Column('tipo_item', sa.Enum('lugar_comun', 'parada', name='tipoitemvisita'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'realizada', 'cancelada', name='estadovisita'), nullable=False),
    sa.Column('hora_calculada_de_llegada', sa.Time(), nullable=False),
    sa.Column('hora_pedida', sa.Time(), nullable=True),
    sa.Column('tolerancia', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_ruta'], ['rutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitas_id'), 'visitas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitas_id'), table_name='visitas')
    op.drop_table('visitas')
    op.drop_index(op.f('ix_turnos_id'), table_name='turnos')
    op.drop_table('turnos')
    op.drop_index(op.f('ix_rutas_id'), table_name='rutas')
    op.drop_index('idx_rutas_geometria', table_name='rutas', postgresql_using='gist')
    op.drop_table('rutas')
    op.drop_index(op.f('ix_pedidos_no_atendidos_id'), table_name='pedidos_no_atendidos')
    op.drop_table('pedidos_no_atendidos')
    op.drop_index(op.f('ix_paradas_id'), table_name='paradas')
    op.drop_table('paradas')
    op.drop_index(op.f('ix_vehiculos_caracteristicas_id'), table_name='vehiculos_caracteristicas')
    op.drop_table('vehiculos_caracteristicas')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_planificaciones_id'), table_name='planificaciones')
    op.drop_table('planificaciones')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_clientes_caracteristicas_id'), table_name='clientes_caracteristicas')
    op.drop_table('clientes_caracteristicas')
    op.drop_index(op.f('ix_vehiculos_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipo_parada_id'), table_name='tipo_parada')
    op.drop_table('tipo_parada')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_email'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_lugares_comunes_id'), table_name='lugares_comunes')
    op.drop_table('lugares_comunes')
    op.drop_index(op.f('ix_invitaciones_usuarios_id'), table_name='invitaciones_usuarios')
    op.drop_index(op.f('ix_invitaciones_usuarios_hash_link'), table_name='invitaciones_usuarios')
    op.drop_index(op.f('ix_invitaciones_usuarios_email'), table_name='invitaciones_usuarios')
    op.drop_table('invitaciones_usuarios')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_documento'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_choferes_id'), table_name='choferes')
    op.drop_table('choferes')
    op.drop_index(op.f('ix_caracteristicas_id'), table_name='caracteristicas')
    op.drop_table('caracteristicas')
    # ### end Alembic commands ###
